### ISSUE TITLE
Add parsing of A4S, A8S Completion

### ISSUE THREAD

**Issue by ReidWeb** [XIVStats/XIVStats-Gatherer-Java#8]
Completion of A4S guarantees the Gobwalker mount.

Completion of A8S guarantees the Faustlet minion.

_Please check spelling_

**Comment by ReidWeb** [comment]
Gobwalker mount is a guaranteed 'group' drop - not for each character - so while this determines 'yes they have completed it' it is not going to match against the majority of characters.

**Comment by AdriaanDeVos** [comment]
This would match against the majority of characters because most players that cleared it once, also cleared it at least 8 times. There are few players that would complete the last raid only once.

While having the mount guarantees that the character has completed A4S; Having the achievement A4S will have for most of the players also the mount.

This will only hold up for previous raid tiers. For the current raid tier it gives a skewed result because of everyone being in progress.

**Comment by Pricetx** [comment]
Thank you for the suggestion. We now record all minions and mounts in the database, so any suggestion along these lines would really be more relevant for the PHP side of things, but we do now have the data at least.
